[quote.epigraph, , John 6:45]
____
It is written in the prophets,
'`And they shall be all taught of God.`'
Every man therefore that hath heard,
and hath learned of the Father, cometh unto Me.
____

== Preface To the American Edition

Daniel Wheeler, a minister of the Religious Society of Friends,
while residing near Petersburg, in Russia,
felt his mind drawn through the immediate operation of the Holy Spirit,
to visit the Islands of the South Sea, New South Wales and Van Diemen`'s Land.
In obedience to this manifestation of the Divine Will,
and having the concurrence of his friends in England, he sailed from the Isle of Wight,
in the beginning of the year 1834, in the Henry Freeling,
a small vessel of 101 tons, purchased for the voyage.
As the object in view was solely of a religious character, her burden consisted only,
besides the necessary stores,
of a small selection of useful articles intended as presents for the natives,
and a quantity of tracts and books, on religious subjects, for distribution;
all purpose of trade being scrupulously avoided.
When entering upon so long a voyage,
Daniel Wheeler could not but be solicitous to promote the spiritual
improvement of those who were to be associated with him.
It was indeed his earnest desire, as he expressed it,
that it might prove to all the ship`'s company "`a voyage towards the kingdom of heaven.`"
In accordance with these views,
the following stipulations were entered into with the captain and crew before sailing:

First--That the Henry Freeling was to be a Temperance ship.
Secondly--That the crew was to be regularly assembled in the cabin twice on every First-day,
for devotional purposes;
and that the scriptures were to be read every morning and evening, in the cabin,
on other days, when both the captain and mate would be expected to attend.
Thirdly--That, as much as practicable, all unnecessary work was to be dispensed with,
as regards the sailors, on the First-day of the week,
to afford them a portion of time for themselves.

In the course of the religious opportunities thus provided for,
Daniel Wheeler was at times engaged, under the quickening influence of Divine Love,
to exercise that gift in the ministry which he had received of the Lord Jesus;
and it will be seen in the following narrative,
that in one instance the discharge of this duty was signally blessed.

It is satisfactory to add, that during a voyage protracted through three years,
the crew of the "`Henry Freeling`" were, with few exceptions,
remarkable for exemplary conduct, not only on shipboard,
but at the various ports at which she stopped,
where they were exposed to the temptations arising out of the unbounded license
attending the intercourse of seamen with the natives of the South Pacific.
After encountering many dangers, and witnessing signal instances of Divine interposition,
Daniel Wheeler returned to England, in the year 1838,
bearing with him ample testimonials of the value of his Gospel labours,
amongst the simple Islanders; and above all, feeling within himself the reward of peace.
