== Preface To the English Edition

Soon after my acquaintance with the subject of the following sketch,
I became so much interested in his history,
as to suggest that he should make a record of some of the remarkable events of his life,
in commemoration of the long-suffering and tender mercy of God towards him.
This, however, he omitted to do,
though he had made preparations for it a few weeks only before his decease.
We are, therefore, furnished with but scanty materials of an interesting character,
except what may be gleaned from his letters,
together with that which the memory of his widow and friends can supply.
But that which will, perhaps, give to the subsequent pages their chief interest,
is the correspondence, on shipboard, between him and Daniel Wheeler,
at the time of his being first awakened to the importance of eternal things.
Daniel Wheeler`'s letters were placed in my hands in 1840;
and I then believed the time might arrive for me to give publicity to them,
with some notice of William Bush himself.
The circumstances of his conversion very strikingly exemplify
the simplicity of the means sometimes employed by the Most
High to bring the sinner to the knowledge of his salvation;
and the narrative exhibits the care of the instrument,
that the work of divine grace should in no degree be marred by unauthorized efforts,
on his part, to promote it.

It may be well to add, that a very few alterations, almost exclusively verbal,
have been made, chiefly in the letters of William Bush.

Edward C. May.

Tottenham, Fifth Month, 1844.
