== A Brief Account of William Bush.

William Bush, the subject of the following brief memoir, was born at Woolwich,
Eighth Month, 1794.
Both his parents were serious people;
but his mother was remarkable for her great meekness and gentleness of demeanour.
She appears to have been anxiously concerned for the spiritual welfare of her children,
earnestly desiring that they might choose the Lord for their portion;
and her memory was very precious to William Bush when,
being himself brought under the power of religion,
he was able to appreciate her character.
Very little is known of his early days: as a boy,
he was of an amiable and quiet disposition; his education was very limited.
In 1807, being thirteen years old, he was apprenticed to a shipwright at Woolwich,
with whom he remained seven years.
During this period, he manifested great industry and attention to business,
but became gay, and grew fond of associating with bad company, in ale houses, etc.,
and indulged in those debasing pursuits common among sailors,
and those connected with them.

On the expiration of his apprenticeship, he began his sea-faring life,
sailing mostly as ship`'s carpenter, in vessels employed in the whale-fishery.
He was a bold and daring seaman; the absence of "`the fear of the Lord,`" as he stated,
had banished the fear of death from his mind, so that in the midst of storms,
when others were afraid, he would not hesitate to undertake the most perilous duties.
In this occupation, he plunged more deeply into sin, and lived in forgetfulness of God.
Though he does not appear to have sunk to the lowest point of degradation,
and on some occasions, manifested considerable moral integrity;
yet he considered himself to have sunk very low,
when brought to the knowledge of the Truth,
and felt that he was indeed as a brand plucked from the burning through
the condescending love and merciful long-suffering of his Redeemer.
He often alluded to the time of "`gross darkness,`"
when he was the willing servant of Satan,
and spoke of the many dangers to which he had been exposed,
and several hair-breadth escapes from death, which he had experienced;
and with an evident and deep sense of gratitude and love towards Him,
who had forgiven him so much, and was therefore greatly loved,
he ascribed these preservations to the protecting Providence of God,
who had borne so long with him,
and had not cut him off in the day of his sin and alienation.

In the latter part of 1833, he was engaged as carpenter, on board the Henry Freeling,
the small vessel in which the late Daniel Wheeler paid a religious
visit to the islands of the north and south Pacific Ocean.`' It
was whilst thus associated with that devoted servant of Christ,
that W. Bush was brought to a sense of his sinful condition,
and to the knowledge of the Truth.
He used to meet with the rest of the crew, who were regularly assembled,
when the weather permitted, for the purpose of divine worship,
after the manner of Friends, and for reading the Holy Scriptures.
These seasons were doubtless profitable to him;
but it was not until he had been about nine months in the ship,
that any striking change took place in his character; and, although for the most part,
complying with the regulations on board, yet, he at times caused uneasiness,
especially at Rio Janeiro,
at which place some of the crew succeeded in introducing spirits into the Henry Freeling,
and William Bush was found the chief actor in the affair.
But he was so struck with the kind,
yet firm and judicious treatment of Daniel Wheeler on the occasion,
when he expected nothing short of exemplary punishment,
that he resolved never to be guilty of a similar offence, whilst in his employment.
It appears, that he was first powerfully impressed by a few words,
which Daniel Wheeler was led to express towards the close of one of their meetings, viz:
"`I wonder whether any of you think of your future state.`"
These may seem common-place words, but they were evidently given to the preacher by Him,
who brought them with such power to the soul of the hearer,
that his peace in the broad way was entirely broken.
When alluding in conversation to this communication of Daniel Wheeler`'s,
he intimated that his stout heart,
which had not experienced a feeling of fear during the alarming storms,
by which the Henry Freeling had been followed, was now brought down and made to tremble.
His feelings were indescribably changed--the words
he had heard rung continually in his ears.
For the four following days and nights,
he was in a state of the greatest mental agony--a new life seemed to have begun in him,
and his thoughts, whether sleeping or waking,
were almost constantly turned to the momentous subject.
In a letter to Daniel Wheeler, after alluding to some particulars of a dream,
which had afforded him much comfort and instruction, he thus wrote, Eighth Month 25th,
1834.

[.embedded-content-document.letter]
--

This dream has worked wonderfully on my mind ever since.
I don`'t know that I ever spent watch without thinking
of the goodness of my great Protector towards me;
how He has protected me through my wicked course of life.
I have daily read my Testament since that time, and the more I read,
the more it brings to my mind my wickedness in my youthful days.
I find I am in darkness.
In hopes to get light (when I go to my berth) instead of sleep, it is prayer and tears.

--

The day after, he writes again to Daniel Wheeler, as follows:

[.embedded-content-document.letter]
--

Since God has been pleased to strike the blow with my flinty heart,
and the tinder is kindling, I hope to catch with the match,
that I may light the lamp--the lamp,
which will keep me in everlasting light out of darkness; as it says in the 12th chap.
of John, and the 35th verse, "`Yet a little while is the light with you.
Walk while ye have the light, lest darkness come upon you:
for he that walketh in darkness knoweth not whither he goeth.`"
And again, in the 46th verse, "`I am come a light into the world,
that whosoever believeth in me should not abide in darkness.`"
I know that I have to fight that great fight against Satan and his temptations.
If I conquer, I am sensible I shall be happy.
My heart is full; it gives me vent by this.

Pray, Sir, excuse my liberty.
I should be glad to say more, but time is short.

--

Daniel Wheeler replied as follows, Eighth Month 27th, 1834.

[.embedded-content-document.letter]
--

[.letter-heading]
To William Bush.

The letter which thou thyself handed to me on the morning of the 25th instant,
although altogether unexpected, was truly welcome,
causing a tribute of humble thanksgiving to arise in my
heart to the God and Father of our Lord Jesus Christ,
"`whose mercy endureth forever,`" that He hath laid
his hand on thee through the medium of a dream,
which He is, at times, graciously pleased to make use of, to awaken poor,
sinful mortals to a sense of their undone state and condition.
As in the dream, when thou asked me, if I knew that man in the sea, I said, "`Yes,
it is the Lord,`" so now say I again, "`It is the Lord.`"
It is indeed a merciful visitation from the Lord to thy poor soul,
extended in the greatness of his love and strength; and therefore,
it is my most earnest desire, that thou may`'st not trifle with it,
or endeavour to set it aside; for,
if thou art not found opposing the designs of Omnipotence in this thing,
by resisting it with rebellion, disobedience, and unbelief,
He will save thee with an everlasting salvation.

That which now convinceth thy understanding and reproveth thee for sin,
is nothing less than the strivings of the Holy Spirit of the Lord Jesus,
unto which thou couldest never have come, or have been in any degree sensible of,
unless the Father had drawn thee by the cords of his everlasting love.
"`No man cometh to me,`" said Christ, "`except the Father draw him.`"
Again, "`No man cometh unto the Father but by me.`"
He also graciously declares that, him that cometh unto me I will in no wise cast out.
Now, I would have thee keep close to this blessed and holy principle of light in thy own mind,
and patiently endure its searching, cleansing operations;
and it will tell thee all things that ever thou did`'st,
that thou may`'st have a full opportunity to repent of every evil deed;
and be assured that, that which is alone able to convince thee and reprove thee for sin,
is also able to convert thee to God and save thee from sin.
Thou wilt then be turned from darkness to light,
and from the power of Satan to the power of God;
and thus death and darkness will come to be changed to light and life
through the Grace or Holy Spirit of Christ Jesus working in thee.
"`Be thou faithful unto death,`"--not only to the
death of every sensual and carnal appetite and desire,
but of the natural life also, if required for the sake of the Lord Jesus,
and He will give thee a crown of Life.
As thou may`'st have dishonoured the Lord God in days that are over and past,
so now thou may`'st be called upon to make a return,
and bring glory to his name by bringing forth the fruits of repentance,
and forsaking of sin.
Thou canst not tell what good effects thy example
in future may have upon the rest of the ship`'s company;
who, beholding thy good works, may be brought also to glorify God on thy behalf.
Repentance towards God, and faith towards our Lord Jesus Christ,
is the only way towards the kingdom of heaven, that blessed place.
But there must be a patient submission and willingness to endure
the various turnings and overturnings of the Lord`'s holy hand
upon thee to make thee meet to be partaker of such a glorious inheritance.

My advice is, that thou consult no man; confer not with flesh and blood,
but let the Lord be thy only teacher; for He teacheth as never man taught;
therefore keep close to Him; keep on the watch constantly towards Him,
and He will lead thee to the place of true prayer, and that of his own begetting;
and I have no doubt but the day will come when thou
wilt be able to say from heartfelt experience,
the Lord hath heard the voice of my weeping; the Lord hath heard my supplication;
the Lord will receive my prayer.
Then that which is now the convincer and reprover of sin in thee,
which judgeth the prince of this world and casteth him out,
will be found to be the Holy Spirit of Truth,
which leadeth out of all error and guideth into all truth;
the blessed and promised Comforter, the beloved of thy soul,
and the chiefest among ten thousand.

I can feel for thy situation, as one that has been himself under the same condemnation,
and knows what he says,--that it is the Lord that
hath visited thee with the day-spring from on high.

[.signed-section-closing]
Thy sincere friend and soul`'s well-wisher,

[.signed-section-signature]
Daniel Wheeler.

[.postscript]
====

I have received thy letter this morning by the steward.
Write to me as often as thou likes, though I may not be able to answer in return,
the motion of the vessel makes it so difficult to write.

====

--

The following letter to Daniel Wheeler appears to have been commenced by William Bush,
before he received the above, during the morning watch, Eighth Month 27th.

[.embedded-content-document.letter]
--

[.salutation]
Dear Sir,

This is the morning`'s thought and deed.
From twelve to four, watch on deck.
About 12:30 min.
A+++.+++ M. the moon arose from the horizon, beautiful and clear,
which called to mind the wonderful works of God.
It was brought to my mind,
that I had much neglected his ways by not reading the Scriptures,
and that I had abused them one day in Jamaica.
I took up the Bible to read it.
I read a few verses until these words came to me, "`Soldiers,
be content with your wages.`"
I hove the Bible down disgracefully, and said as much as if it was not the work of God,
but the work of man, to keep the poor people in subordination.
This filled my heart, and worked much on my conscience.
At 4 a.m. went below, with my heart full--all thought of sleep was gone;
I prayed to God to forgive me, and wrote a little till six.
Went into my berth, and after my new form of going to bed, paused some time,
then laid myself down to sleep, full of thought;
it must have been seven before I went to sleep, and at eight I awoke,
full of wonder that I did not feel sleepy.
But why wonder at that?
The Lord is as able to satisfy me in one half hour with sleep,
as He was to satisfy the multitude with the five barley loaves and the two fishes.
The mercies of the Lord are coming to me minutely (every minute?),
and his wonderful works.

--

William Bush then proceeds to relate a remarkable preservation
which he had experienced some years before,
during a storm, in which one of his companions was killed by his side,
bringing to his mind the words of the Lord, "`One shall be taken,
and the other left,`" and thus concludes:--"`This
shows that the Lord has always been where I was,
but I would not look on Him.
Oh God, forgive a wretched sinner that I am.`"

On the night of Eighth Month 27th, he again writes:

[.embedded-content-document.letter]
--

From 8 to 12 P. M. watch on deck.
The night is rugged--the Lord has been kindly with me,
bringing to mind my youthful wickedness, such as playing at cards in ale-houses,
going home at all hours of the night, finding my poor mother sitting by the fire-place,
with sometimes a little fire, at others none, after a hard winter day`'s work,
waiting for her wicked son, to let him in.
This had no small work on my conscience.
I am happy that you are acquainted with my feelings as to sin,
but not to the weight of my sins and wickedness.
I am sensible how grateful I ought to be to my blessed Redeemer,
who has snatched me from the claws of hell, and brought me to the blessed light of life,
for He has had compassion upon me.
He has again showed me, that many,
who have followed a place of worship for years and years,
have not come to that light which stands now before me.
This morning the Lord induced me to address all my
shipmates thus,--I received a letter from Mr. Wheeler,
and in case of anger, the devil may enter your minds some time or other,
to say I held a conspiracy against you.
Here is the letter, and I wish you all may read it--I am sure it will not do you any harm.
This is a fine morning to me, though cloudy weather.
My heart feels light, and more reconciled, thanks be to the Lord.

Thursday, 28th, A. M. I feel confidence that the Lord will forgive me, and pardon my sins.
Sir, if you have any old books that will afford one glimmer to this precious light,
I should be very thankful for them.

--

The following reply was sent by Daniel Wheeler, Eighth Month, 29th:

[.embedded-content-document.letter]
--

[.letter-heading]
To William Bush.

I am comforted to find from thy letter, sent this morning by the steward,
that thou feels a little relieved and lighter, since having done what seemed called for,
as regards communicating the contents of my letter to thy shipmates,
in order to prevent unfounded suspicion on their part.

I am very thankful that the work of repentance is still going on in thy heart,
and that the Lord, in the riches of his tender mercy and compassion,
is setting thy sins in order before thee, that so they may go beforehand to judgment,
and through the precious blood of the Lamb of God, Christ Jesus, be washed away,
and blotted out forever.
I am fully aware, that the remembrance of thy past conduct, in the waste of time,
which is graciously bestowed upon us for the great purpose of working
out the salvation of our never-dying souls with fear and trembling,
and not to spend in sinning against the Lord, in cards and other wicked practices,
in the very haunts of Satan, such as ale-houses, etc., etc.
I say,
I am fully aware that the remembrance of these things must now fill thy heart with shame,
and remorse, and sorrow;
and it is these painful conflicts that stir thee up to repentance and
amendment of life--yet it is not the sorrow of those who have no hope,
but it is that sorrow that worketh repentance, not to be repented of, when it is over,
because it will ultimately be found to be the forerunner of endless joy in the Lord.

I do not wonder at thy being desirous to read any book that
would be likely to add one glimmer to that precious light,
but I should be very sorry to contribute to cause that precious light to be neglected,
by lending thee any book at the present time,
lest it should unhappily be withdrawn or darkened.
"`If the light that is in thee be darkness, how great is that darkness;`" Matt.
6th chap.
23d verse.
I know of no book whatever, suitable for thee to read, in the present state of thy mind,
but the Holy Scriptures.
This would be safe,
because the main object and bent of the Scriptures is to turn the people to Christ Jesus.
I consider thy desire to read is a very plausible snare,
laid by thy soul`'s great enemy to draw the attention of thy mind _without_ thee,
from the light of Christ _within_ thee;
and then his crafty purpose would be fully answered,
for Satan well knows that he will soon lose all his power over thee,
if thou steadfastly follow this light,
because it makes manifest his works of sin and darkness to thy mind.

Now I believe that a man may read, even in the Scriptures, the best of all books,
until he neglects this precious light of Christ, and goes away from it, although,
at the same time, these very Scriptures direct and point to the Saviour.
It was the exact case of the Jews, who crucified him--they had the Scriptures,
and thought themselves secure of eternal life.
But what saith the Prince of life, Christ Jesus, unto these Jews?
Read chap.
5th John, 39th verse, Search the Scriptures, for in them ye think ye have eternal life;
and they are they which testify of me, and ye will not come to me,
that ye might have life.
There is no eternal life, but for those who believe and come to Jesus.
See his own gracious invitation in Matt.
11th chap., 28th verse,
"`Come unto me all ye that labour and are heavy laden (with the weight of sin and iniquity),
and I will give you rest.
Take my yoke upon you, and _learn_ of me, for I am meek and lowly in heart,
and ye shall find rest unto your souls, for my yoke is easy, and my burden light.`"
We must come to Him, and _learn_ of Him, the meekness and lowliness of heart,
which alone can procure rest unto our souls.
Now, any book or thing which is suffered to divert the attention
of thy mind from the precious light of Christ within thee,
would be taking thee away from Him, and not bringing thee to Him,
who alone can show thee thy sins, and save thee from them.
If thou neglect this light that is in thee, the work of repentance will cease,
and Satan will again prevail over thee.
I hope thou wilt see the tempting snare, which is laid for thee,
and therefore "`watch in this light.`"

[.signed-section-closing]
Thy sincere Friend,

[.signed-section-signature]
Daniel Wheeler.

[.postscript]
====

Take sufficient food and rest--in short, take care of thyself.

====

--

In this letter, the true wisdom of the writer is strikingly observable,
and his right concern,
that the eye of the new convert should be kept singly
directed to the pure light of Christ,
the quickening Spirit to God and the Word of His grace,
as being that which could alone build him up and give him an inheritance
among all them that are sanctified thus manifesting his earnest desire
that the work might be altogether the Lord`'s. The heart had been touched
by Him--its sinfulness had been made manifest and reproved,
and it had been given him to see that all his life
long he had been in bondage under the power of Satan,
and He only,
who had thus revealed Himself unto him as a "`convincer
of sin,`" and had caused him to feel the need of a Saviour,
could, by the further operations of His power,
bring him to the saving knowledge of "`the Lamb of
God which taketh away the sin of the world.`"

Eighth Month 31st, 1834.
William Bush again addressed Daniel Wheeler, in reply to his last letter:

[.embedded-content-document.letter]
--

[.salutation]
Dear sir,

I received your letter by the steward, on the 29th, and was very thankful for it.
I was very happy that you showed me my error.
This showed me my darkness, John 1:6, "`The light shineth in darkness,
and the darkness comprehended it not.`"
The light which your letter affords me, it is precious;
it shows me that I must not refrain from the Scriptures,
but seek the Light of God more abundantly; and that I must watch,
for I know not the hour when the Son of man cometh.
I pray to God to keep me in the way of Truth, and from the power of Satan,
and that I may return again to my friends.
What a happy hour it will be.
When I took a last farewell of my brother, and promised him, he would see a change in me,
he in a flood of tears replied, "`God send your poor mother, if possible,
would leap out of her grave to witness it, though she said always you would be rich;
and I hope it will be in the kingdom of heaven.`"
She was a member of a Baptist chapel for years before my time.
The night before her death, she sent for all my brothers and sisters;
then telling the eldest to take his pen, and set down how all things were to be,
and wishing my sister to keep on the house,
that the straggling sheep may always have a home to come to.

--

He then alludes to the happiness of his mother, in the prospect of death, and continues:

[.embedded-content-document.letter]
--

Oh! what a blessing is that to be ready when called for.
I promise you, Sir, that my daily prayer is to the Almighty God, to keep me in Truth,
and from the power of Satan; Matt. 7:7. "`Ask, and it shall be given you; seek,
and ye shall find; knock, and it shall be opened unto you.`"
Again, in 8th verse, "`For every one that asketh receiveth, and he that seeketh findeth,
and to him that knocketh, it shall be opened.`"
Sir, I return my hearty thanks for your kindness, and may God reward you.

[.signed-section-closing]
Your humble servant,

[.signed-section-signature]
William Bush.

--

Whilst the Henry Freeling was at Hobart Town,
William Bush attended diligently the little Meeting
of persons in that place professing with Friends;
and on these occasions, his deportment bespoke a mind reverently waiting upon the Lord:
and he sometimes conversed with persons with whom he met,
and whom he believed to be walking in the fear of God,
upon the great mercy which had been shown to him.
He was remarkably careful for the welfare of the vessel,
on board of which he usually kept the captain`'s watch:
on the passage from Hobart Town to Sydney, on a dark, foggy evening,
he felt an inclination to take a book upon deck out of his regular course;
and quickly discovered the glimmering of the fires of the natives on the shore.
It proved, that the vessel had been driven by a current too close to the land;
and from the direction in which she was standing,
would have been on the rocks in a few minutes, but for this circumstance.
The occurrence is alluded to at p. 289, [.book-title]#D. Wheeler`'s Journal,#
but W. Bush is not there mentioned as the instrument of deliverance.^
footnote:[See also James Backhouse`'s [.book-title]#Australian Narrative,# p. 231.]

From this period, we know but little of what passed in William Bush`'s mind,
till the Twelfth Month of the same year, when being at Sydney,
he had leave of absence for a short time.
Whilst on shore,
a secret impression on his mind induced him to follow a woman of respectable appearance,
to a place of worship, where he heard a sermon preached by Dr. Marshall,
at that time surgeon on board the _Alligator,_ sloop of war.
The discourse was very applicable to the state of William Bush`'s mind,
and was quite a comfort to him.
We have not been able to meet with a letter,
which he wrote to Daniel Wheeler on this subject, and to which the following is a reply,
dated Twelfth Month 17th, 1834:

[.embedded-content-document.letter]
--

[.salutation]
To William Bush,

The letter thou sent me by the steward, conveyed information, which is very comforting,
because, I think the circumstance of thy going to the chapel,
and meeting with Dr. Marshall, in the manner that thou describes,
must be very confirming to thy mind;
and in tender mercy permitted to encourage thee and strengthen
thee to draw nearer and nearer to that good and gracious God,
who hath done such great things for thee.
He is, indeed, a Spirit, and must be worshipped in spirit and in truth;
and a measure or "`manifestation`" of his blessed Spirit,
is mercifully given to every man and every woman to profit withal.
And this is no other than the Spirit of the Lord Jesus,
who died for the sins of all mankind, the just for the unjust, to bring us to God.
He ascended up on high; He led captivity captive, and received gifts for men,
for the rebellious also, that the Lord God might dwell among them.

In order to come to a better acquaintance with the Holy Spirit,
we must give up ourselves _wholly_ to its sure and certain guidance,
for it is the whole heart which the Lord requireth of us;
a divided heart he will not accept.
And what we go to meeting for, is to wait upon God in spirit, who is a Spirit,
and must be worshipped in spirit and in truth.
If we are diligently persevering thus to wait upon Him in reverent stillness,
watching unto prayer, He will, in due time, enable us to silence all our own thoughts,
bringing every one of them into captivity to the obedience
of Christ`'s blessed Spirit within our hearts,
who shall then rule and reign, whose right it is.
And having by the mighty working of his glorious power in our hearts,
cleansed us from all sin, we shall indeed come to know Him to be "`the Lamb of God,
that taketh away the sin of the world.`"
And He will, at seasons, fill us with joy and peace in believing, to his own praise,
and the glory of God the Father, who is God over all, blessed forever.

It is the great privilege of the Christian,
who believes in the Spirit of Christ within him,
that there is at all times an opportunity of seeking
for a better acquaintance with this heavenly,
indwelling principle of light, life, and love; not only when we go to meetings,
but when we lie down, and when we rise up, when we are walking by the way,
or during the watches upon deck, day and night; even in the midst of our work,
or when amongst other men,
we can at all times turn the attention of our minds to this blessed Spirit,
and watch towards its temple, which is the human heart,
by keeping down our own thoughts and imaginations,
and thus continually offering a spiritual sacrifice, which is ever acceptable to God;
who seeth in secret, and will reward us openly, and of whom it is written,
"`He that believeth on Him, shall not be ashamed,`" and who hath graciously declared,
"`They shall not be ashamed that wait for me.`"
For if we are faithful in seeking Him, and in patiently waiting for Him,
He will not fail, from time to time, to renew our spiritual strength,
and finally make us more than conquerors over all our souls`' enemies,
through the Holy Spirit of Him who loved us,
and washed us from our sins in his own blood.

[.signed-section-closing]
Thy sincere Friend,

[.signed-section-signature]
Daniel Wheeler.

--

After the foregoing we have no letter of William Bush`'s till the Third Month 24th, 1835,
when he again wrote to Daniel Wheeler.

[.embedded-content-document.letter]
--

[.salutation]
Dear Sir,

My heart has been desirous to speak to you, but the way has not been clear.
When we were at Hobart Town,
James Backhouse preached on the coldness that came
over young beginners in the belief of God,
which I have witnessed and been sensible of.
I have stirred and aroused myself from it.
It has been shown me that I have thought too much on the things of this world,
and not of the world to come.
I have told my shipmates to trouble me no more with navigation;^
footnote:[William Bush was accustomed to give instruction to his shipmates in navigation,
a good knowledge of which he appears to have acquired;
he kept his own log-book of the course of the Henry Freeling.]
but I am about to learn the course and distance to
that heavenly port of everlasting rest.

Dear Sir, I find great benefit in reading [.book-title]#Piety Promoted;#
and being sensible you lent me that book for the good of my poor sinful soul, I, Sir,
return my most humble thanks.

--

He then goes on to state, how much he had been impressed with a portion of Scripture,
which Daniel Wheeler had read to them on the preceding First-day, so much so,
that he had left his berth and told a fellow-sailor his opinion respecting it; and adds,

[.embedded-content-document.letter]
--

Again I talked of the Almighty power of God;
how he was able to build up and to pull down; as king Herod, how he was eaten of worms;
and Nebuchadnezzar, how he ate grass like an ox;
and how God raised Peter up out of the strong prison; and many more things.
And I felt the Lord blessed me in spirit, and I had a fine night.
Oh, that I may live to worship the Almighty God in spirit and in truth.

[.signed-section-signature]
W+++.+++ Bush.

--

Daniel Wheeler wrote the following reply on the same day:

[.embedded-content-document.letter]
--

[.salutation]
To William Bush,

I am glad to find by thy note of this morning,
that the good work of the Lord is going on in thy heart,
and I hope thou wilt be strengthened to see the difference
between the two powers at work in thee;
so that thou may`'st more and more cleave to the one and turn thy back on the other;
for assuredly, that,
which has a tendency to bring coldness and indifferency over thy mind towards God,
is the power of Satan, the grand enemy of thy soul, and if not resisted,
will lead to the way of death and darkness; but that,
which shows thee and makes thee sensible,
that thou hast thought too much about the things of this world, is the power of God,
through his saving grace,
shed abroad in thy heart in the greatness of his love towards thee, and which,
if watched unto and attended unto, will rescue from death and darkness,
and lead thee to light and life.
So that if thou faithfully maintains a strict watch over thy thoughts as they arise,
thou wilt be led to pray more and more in thy spirit, and the Lord most High,
who is a God ever hearing and answering prayer of his own begetting,
will enable thee by the light of his Holy Spirit to discover
from whence every thought arises and springs,
whether from a good or evil root, so as thou may`'st trace unto what it would lead.
If thy thoughts have a tendency, as in the instance before us,
to lead to coldness and indifference towards things of eternal consequence,
and fill thy mind with desires after the things of this perishing world,
or to the gratification of self-ends and self-interest, or any worldly object whatever,
so as to cause thee to overlook and neglect the Lord`'s mercies,
which have been great towards thee;
then thou may`'st be sure that this is the work of the power of darkness.
But if, on the contrary, thou art shown, that thou thinks, or hast thought,
too much about the things of this perishing world, then thou may`'st depend upon it,
that this is the visitation of Divine Love in order to save thy soul.
To this, therefore, cling as for thy life, with all thy might;
and as thou perseveres thou wilt in time be favoured to find,
that the temptations of the enemy grow weaker and weaker,
and that the power to resist them is stronger and stronger.
And as we thus walk in the spirit, we shall not fulfill the lusts of the flesh: therefore,
Watch and pray,`' (the only sure protection against the wiles of the devil,
which our Lord Himself enjoined,) "`lest ye enter into temptation.`"

[.signed-section-closing]
Thy sincere Friend,

[.signed-section-signature]
Daniel Wheeler.

[.signed-section-context-close]
24th of Third Month, 1835.

[.postscript]
====

P+++.+++ S.--Apply to me at any time,
and I will endeavour to render thee all the information in my power.

====

--

The next day, William Bush communicated a dream by letter to Daniel Wheeler,
which had been very significant to his own mind.
In allusion to it, the following remarks are found among Daniel Wheeler`'s memoranda:

"`Having perused the above with attention,
there seemed something moving on my mind towards
this living monument of the Lord`'s mercy;
and apprehending that it was prompted by that love,
which suffereth long and is kind,`' and which ever waiteth graciously with outstretched
arms to welcome with heavenly rejoicing the poor lost wanderer,
that he may return, repent and live, the following lines were penned in answer:`"

[.embedded-content-document.letter]
--

[.letter-heading]
To William Bush.

Be assured, that thy writing of the Lord`'s mercies, instead of offending,
will always gladden my heart.
I hope the dream thou hast just been favoured with will
make a lasting and grateful impression upon thy mind.
To me it not only seems to convey great encouragement, but deep instruction,
as well as serious warning.
After such a merciful and continued visitation of everlasting love towards thee,
if thou art not saved, thy destruction will be of thyself.

In the first place, thou art plainly shown, for thy encouragement,
that in turning from thy wicked ways, although the way may be, and is,
attended with difficulty, yet if thou perseverest in faithfulness,
thou wilt not fail to receive a reward; betokening, at the same time,
that thy past sins and iniquities, although dark as crimson,
in unutterable mercy will be washed in the precious blood of the Lamb of God,
that taketh away the sin of the world, and with thy transgressions,
will be blotted out as a cloud forever.
Secondly, thou may`'st see by the rock, which appeared to be in constant motion,
the unsettled, unstable condition, and the great uncertainty of everything in this world,
that belongs to, or is connected with human life.
Thirdly, it holds out an awful warning,
that if thou slight and reject such renewed offers of divine love and regard,
and turn thy back on Him, who hath evidently called thee to glory and virtue,
and hath measurably turned thee from darkness to light,
instead of the joyful sound of "`Come,
ye blessed of my Father,`" it will be the woful one of "`Depart from me,
ye that work iniquity,`" and the reward will be lost forever.
"`How shall we escape if we neglect so great salvation?`"
Then "`whilst it is called today`"-- while life and health are vouchsafed, linger not,
for this is the accepted time this is the day of
visitation--this is the day of salvation.

It is no marvel to me, that a sight of the sea was brought before thy mind in thy dream,
because it should never be forgotten,
that it was upon the mighty ocean that thou wast
first aroused to a sense of thy sinful state,
and where thou hast witnessed so many great deliverances.
And perhaps the sense of coldness and indifference, before hinted at,
began to take place whilst at Hobart Town, or Sydney,
at which places there was great danger of unfaithfulness and sliding backwards,
and mixing with wicked companions;
and therefore thou may`'st yet more have to look at the sea, and remember it,
as the place where again the God of Heaven has condescended to renew the
visitation of his marvellous and matchless love towards thee.
Our only place of true safety is the watch tower, whether on sea or land.
"`What I say unto you, I say unto all, watch,`" was the declaration of Him,
who knoweth what is in man, and best for him--for He searcheth all hearts,
and--mind--understandeth the imagination of the thoughts.
If we seek Him, He will be found of us; but if we forsake Him, He will forsake us,
and cast us off forever.

[.signed-section-closing]
Thy sincere Friend,

[.signed-section-signature]
Daniel Wheeler.

[.signed-section-context-close]
26th of Third Month, 1835.

--

About five months after this, when off the island of Tahiti,
William Bush`'s health became so seriously affected,
that it was thought needful to leave him on shore,
although his own wish was to continue the voyage without regard to the result,
as he could not bear the prospect of being separated from one,
who had been made use of in bringing him to a knowledge of the Truth.

It appears from a former letter of William Bush`'s,
as well as from his remarks in conversation, when alluding to this period,
that there had been a decline from the fervour of first love,
and that a coldness and indifference to those things that make for salvation,
had insensibly stolen over his mind.
Such a state of feeling could scarcely exist,
without some external manifestation of it in his daily walk and conversation.
Daniel Wheeler`'s fear for the stability of this new convert,
is evident in the last letter he wrote to him,
and which was handed to him soon after parting.
In it, Daniel Wheeler forcibly sets before him the awfulness of backsliding,
after the great and manifold mercies, which he had experienced at the Lord`'s hand,
and "`entreats him to watch and pray,
and to fast from the gratifying things of time and sense, to take up the cross,
the daily, hourly cross, to his corrupt will and inclination,
or he could never follow Christ, or be where He is.`"

Daniel Wheeler and William Bush only met once again.^
footnote:[In Third Month, 1840,
shortly before Daniel Wheeler left this country on his last visit to America;
he had called at W. M.`'s office, Houndsditch, when, at this very juncture,
William Bush went there to learn some tidings of him.]
The interview was a deeply interesting one.
William Bush`'s heart was too full to communicate all he wished,
but enough was said and felt to satisfy his friend that he had not laboured in vain;
indeed, so convinced was he of his heavenward progress, that he afterwards remarked,
that had he "`gone to the South Seas for the gathering of that man only,
he should have thought himself richly repaid.`"

To return to the time of William Bush`'s illness at Tahiti; being now left to himself,
we may readily conceive how bereaved and solitary was his condition;
but he had learned where to look for help,
and although at the time he felt his being thus left alone, a severe trial,
yet he afterwards had gratefully to acknowledge,
that all things were rightly ordered by infinite wisdom.
The individual who had been made instrumental of so much good to him,
and on whom he might otherwise have improperly leaned, being taken away,
he was brought to feel the necessity of a more entire reliance on the Lord alone,
who graciously condescended to guard, guide, and teach him.
It appears to have been about two months before his health was so far
reestablished as to enable him to take passage in a homeward-bound vessel.
During the time of his sickness on the island,
his mind was seriously concerned in reference to his future course of life;
he knew how sinful it had hitherto been, and he,
who felt no fear when engaged in folly and wickedness, and who,
under the influence of the god of this world, became blind and obdurate,
was now tremblingly alive to his own weakness,
and earnestly craved to be kept from all evil;
he longed for the time when he should be able to lead a quiet life on shore, and,
instead of joining with the wicked,
unite with Christian brethren in the public worship of his God.
During his voyage to this country,
whilst endeavouring to keep his eye singly directed towards the Lord,
it was impressed on his mind,
that it would be right for him to quit the occupation of sailor, and to settle in life;
and at the same time, he seemed to be directed to one,
with whom he had been`" acquainted almost from childhood,
as the companion of his future path.
The belief that such a course was consistent with the divine
will was remarkably confirmed by subsequent occurrences.
On reaching Woolwich he found that his former home was broken up,
his sister having died suddenly a few weeks before.

M+++.+++ A. H., the individual before alluded to,
had hitherto been able to look upon him only as a wanderer in the path of sin,
but she felt an interest in him on his mother`'s account, to whom she had been attached,
and of whose religious character she had formed a high estimate;
and finding that he was staying at a public-house,
she recommended him to take private lodgings,
which she knew would be more congenial with his late mother`'s wishes.
On the following First-day after his return, he called on M. A. H., who inquired,
where he was going; he replied, "`To Meeting;`" and being asked where, answered,
"`In my own room.`"
This was the first time she had any reason to think
a work of religion had been begun in his mind;
it was however a manifestation of seriousness, which she then could scarcely understand.
During the week, he was taken ill,
and M. A. H. kindly attended upon him during his sickness, in the course of which,
it became more clear to his mind, that she was his allotted helpmeet,
and they were eventually married, in the Seventh Month, 1836.
Soon after this, they removed to Blackwall, where he resided,
following the occupation of shipwright, till the period of his decease.
Their union was a happy one,
because they were both led to "`seek first the kingdom of God and his righteousness.`"
And all things needful were added unto them.

In the Seventh Month, 1840, the writer became acquainted with the subject of this Memoir,
on the occasion of his informing him by letter of the death of Daniel Wheeler;
when he received the following reply.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
July 20th, 1840

[.salutation]
Dear Sir,

After reading your kind letter on the 17th,
it caused a tribute of thanksgiving to arise in my heart,
when I thought that thou shouldest take knowledge of a poor sinful creature like me.
When I read of my dear friend`'s decease, I felt sorrow at heart; but, God be thanked,
I am able to testify that his labour was not in vain in the Lord,
forasmuch as he was made instrumental in the hands of the Lord, to snatch, as it were,
my poor soul from going down into the pit.
I attended Friends`' Meeting at Houndsditch, on First-day morning;
but I cannot express what I felt in my heart towards
all Friends for what they have done for me.
Sir, should next First-day be convenient, and God willing,
I should be very happy to wait upon you.

[.signed-section-closing]
I remain your humble servant,

[.signed-section-signature]
William Bush.

--

He came as proposed, and was deeply affected by hearing what was communicated,
in reference to one so justly dear to him; so tenderly indeed did he love him,
as to shed tears, and even to leave the room, overcome by emotion,
on hearing a letter read, in which the death of Daniel Wheeler was alluded to.
He dwelt with evident pleasure on the many deliverances he had experienced,
and on the abundant mercies of the Lord towards him,
especially those which were associated in his memory with his departed friend,
the influence of whose mind he had himself powerfully felt,
and seen to be so great in others, during their memorable voyage together.
Serene and tranquil in the assurance that all things would work together for his good,
Daniel Wheeler was preserved in a holy quietude,
which enabled him to encourage those around him in the midst of the most violent storms.
This influence was felt by William Bush,
who then knew but little of the operation of that power,
which so signally sustained this devoted man.
He used to relate that he had seen him, when they were in the most imminent danger,
with a smiling countenance, pat one of the ship`'s boys, when in tears, on the cheek,
telling him "`not to be frightened,
for he was as safe as if he was in a king`'s palace.`"
Indeed,
the voyage in the Henry Freeling appeared to be a
favourite topic of conversation with him;
and it was interesting to hear his detailed description of many of its remarkable occurrences.

In the autumn of 1840, William Bush was visited by an illness, which threatened his life;
at which time, the following letter, which strikingly exhibits the assurance of faith,
was received from him.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Blackwall, October 14th, 1840.

[.salutation]
Dear Friend,

Having been afflicted with a rapid fever, I write to inform you of the state of my mind,
seeing it is sweeping me away to that place appointed for all living.
The attack commenced on the 7th. I am now examining myself.
I cannot find the weight of any of my sins remain--no,
not the weight of a feather on my mind.
I feel that the blood of Jesus has cleansed me from all sin,
and has given me that peace of mind that passeth knowledge.
I find it good to wait on the Lord, and how true it is, I renew my strength;
and being able to take hold of the hope that is set before me in the Gospel,
I rejoice with joy unspeakable and full of glory.
O, may the Spirit of Truth be with you, and all your dear family.

[.signed-section-signature]
William Bush.

[.postscript]
====

May the Lord bless you all for his own name`'s sake.
Farewell all; if you see me again in the flesh, it must be quick.

====

--

After such an account, I hastened to see him:
and never shall I forget the peaceful--the joyful state of his mind; indeed,
his letter had but simply portrayed what was then witnessed,
and what was the ground of his rejoicing.
He related, that the evening before, when in a peculiarly happy frame of spirit,
it occurred to him,
"`I`'ll pray;`" but the thought arose--"`I have nothing to pray for;`" it then seemed
to be said within him "`Glorify God;`" and truly he was enabled to do so;
for never during twenty-five years,
in which I have frequented the bedsides of the sick and dying,
have I met with an instance in which this was more conspicuously done.
He seemed overcome with the sense of the Lord`'s condescending love and goodness;
his heart was filled with praises, and his mouth spake out of the abundance thereof.
It was, indeed, a memorable season,
and one in which the hearts of those present were united
with his in thankful adoration of the Father of mercies,
whose holy presence was so signally felt among them.

Before leaving him, it was thought right to express that, in case of his recovery,
he must not expect always to have the sun thus above the horizon.
He replied, "`I do not, but I must enjoy it whilst it is so.`"
From a letter received two days after, the following is extracted; being very weak,
he had written it in pencil:

[.embedded-content-document.letter]
--

[.salutation]
Dear friend,

Having, through divine power strength this morning to write to you,
I feel very thankful to Him who does all things well.

I still continue about the same.
I was very happy to hear that you got home safe,
and I was happy to receive yours at 1 o`'clock p.m. You desired me to keep silence.^
footnote:[A caution had been given him not to fatigue himself by unnecessary conversation.]
Two hours after you left me,
my sister and her husband came to see me the Lord opened my mouth,
and I was supported to declare "`the truth as it
is in Jesus;`" and my poor sister was as +++[+++one]
brokenhearted all the time.
I also wrote a long letter to my brother and sister at Woolwich,
upon the truths of religion, and was wonderfully borne up at this time.
I all night felt the presence of the Lord, and was, with much resignation,
enabled to wait the Lord`'s appointed time.
At one time I thought it very near, and then again fell into a sweet sleep,
and when I awoke, I had to declare it was like sleeping in the arms of Jesus.
No more at present; but praise the Lord, oh my soul, and all that is within me,
praise His holy name.

The Lord be with thy whole house.

--

On another visit to him, six or seven days after the former, I found him much recovered,
and in the same peaceful and happy state of mind;
and the interview was both instructive and refreshing.
It will be observed, by what is stated in his next letter,
that the sensible enjoyment of the presence of his beloved,
at whose table he had been permitted to sit, and to eat and drink,
to the satisfying of his hungry and thirsty soul,
was not permitted to continue without intermission;
but he had again to experience the hiding of God`'s countenance,
that he might know that all his fresh springs were in Him alone.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Blackwall, 11th November, 1840.

[.salutation]
Dear Friend,

Though I have not written to you, since I saw thee,
yet I can say I have very often remembered thee with much love,
for the great kindness thou hast shown towards me, an unworthy sinner.
I received thy kind letter, at 4 p.m., Monday, for which I was truly thankful,
inasmuch as it caused that light to shine, which for two days has been hid from my eyes.
Feeling liberty, I will tell thee what I felt.
Although it was called the Sabbath, it was not a Sabbath to me,
for I was made to cry out, "`Why art thou cast down, oh my soul,
and why art thou disquieted within me?-hope in God, for I shall yet praise Him,
who is the health of my countenance, and my God.`' Dear friends,
I cannot find words to describe my dark feelings.
I took up the Scriptures but could not read them,
but with that cloud of darkness before my eyes, which grieved my poor soul.
But when I look at Job`'s saying, "`Shall we receive good at the hand of the Lord,
and shall we not receive evil?
This is, indeed, a lesson for me, to know the believer`'s path is not all sunshine.

I must again thank thee for that little treasure, called [.book-title]#Shewen`'s Meditations,#
after reading which, and studying for myself, I feel convinced, we can with God`'s help,
and must, before we can enter the kingdom, live without sin.
Last week, two friends came to see me--our discourse was upon sin.
I said, Is it impossible to live without sin?
They answered, If you can you are the first man.
I said--I believe I can do all things, through Christ strengthening me,
and that we must live without sin before we can enter the kingdom.

I think next week, if God be willing, to go to my work.
I believe that my heavenly Father will answer my prayer,
and my Saviour`'s--not that He would take me out of the world, but keep me from the evil.
I have made bold to lend your book to one who had much desire to read it,
with the promise of much care.

--

William Bush, one day, called on a Friend,
for the express purpose of knowing what was the belief of the Society,
on the doctrine of freedom from sin,
manifesting great astonishment at having _unexpectedly_ found,
that any who had felt the power of religion in his own soul,
could entertain even a doubt on the subject; and he was still more astonished to find,
that most of the "`different churches`" believed in the
necessity of continuing in sin during this life;
on being told what were the views of Friends,
his countenance seemed to beam with a hallowed joy, and he said,
with a tone of evident satisfaction, "`I thought Mr. Wheeler did not think so,`"--adding,
with an emphasis, to which no description can do justice, "`What! am I,
who served the devil so many years, to continue to do so till the end of my days?
Cannot my Lord and Master make me as much _His_ servant, as I have been that of the devil?
I cannot argue on the subject, but I do not find such, a thing in the Scriptures;
neither am I told so __here,__`" laying his hand on his breast.
He quoted the passages,
"`I press towards the mark for the prize of the high calling of God in
Christ Jesus,`" and "`His servants we are to whom we obey,`" etc. etc.

He again writes under date of January 4, 1841.

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

I received your kind letter and parcel,
and was very glad to find account of the servants of the Lord, James Backhouse,
and G. W. Walker, as I was a little personally acquainted with them.
Kind friend, please to excuse me for not writing before.
I have to work from dark to dark -- and when in the right mind to write to thee,
lacked opportunity.
I thank God, for He has restored me to perfect health; and I am able to say,
my affliction was not grievous,
as it was a time of refreshing from the presence of the Lord.

I was invited to a meeting held for spiritual conversation, and being lately afflicted,
I was called upon to speak.
I said, I found the Lord a very present help in every time of need.
That is all I had to say.
I had not sat long before these words came to my mind.
As every man hath received the gift, even so minister the same one to another,
as good stewards of the manifold grace of God.
I had to tell them what the Lord had done for my poor soul, that it was not in preaching,
or in much talking, but in silent waiting on the Lord, with the exception of these words,
"`I wonder whether any of you think of your future state.`"
I had to tell them, I was for days and nights in prayers and in tears,
under the weight of all my sins,
and the worst of them I committed five years and six months before;
and that I never thought of it in all that time,
until the Lord told me all things that ever I did.

I return the book of J. Pike, which I have read with much interest,
and our dearest friend, Daniel Wheeler`'s [.book-title]#Journal,# as my friend,
W+++.+++ M. made me a present of one, which I prize much.

--

By the foregoing letter,
we see that William Bush was advancing in the spiritual life himself,
trusting in the Lord more and more, and encouraging others to trust in Him,
whom he had found to be a very present help in trouble.
For some time after his marriage,
although he had a decided preference for the meetings of Friends,
yet not knowing of one within his reach, he usually attended the Independent chapel,
of which his wife was a member; he gladly took his share in visiting the sick,
and never allowed the idea of danger from infection to weigh with him,
so as to prevent his cheerfully going to any of this class.
He could speak well of the name of the Lord from heartfelt experience,
and was never more happy, than when testifying of what He had done for his soul;
and knowing of a truth,
that every one who thirsteth may "`come to the waters,`"
and he that hath no money may
"`come, buy, and eat,`" he earnestly desired that all should come
and partake "`without money and without price.`"

On one occasion,
having at the request of his wife gone to a "`prayer-meeting,`"
he was asked to take part in it;
it was then he felt how widely his own views differed from theirs, and he replied, "`No,
I cannot do it.
I have but little religion, and,`" placing his hand on his heart, "`it is all here.`"
When referring afterwards to this circumstance, he said, "`But sometimes,
when by the sick-bed of those I visit, I am enabled to pray, and the words come,
almost faster than I can utter them.`"
The above and similar occurrences caused him to become
increasingly dissatisfied with a ministry,
which was exercised at an appointed time,
and without waiting upon Him who "`is a Spirit and
must be worshipped in spirit and in truth,
for renewed qualification.`"
It was a great trial to him to separate from his beloved wife in public worship, but,
feeling more and more drawn from the teachings of men, and that,
however consistent the matter expressed might be with the truths of Scripture,
yet that these ministrations did not tend to his edification and comfort,
but even sometimes kept him from that communion with God, which his soul longed for,
he was best satisfied to leave this mode of worship;
and having heard of the meeting of Friends at Ratcliff,
which was about three miles from his home,
he usually attended it twice on First-days until his death.

The following are extracts from a letter received from him dated: Fifth Month 21st, 1842.
After alluding to the defection in the Church, he says,

[.embedded-content-document.letter]
--

But we must not think as though some strange thing had happened,
but such as is common to man.
Poor man hews out to himself cisterns, broken cisterns, that can hold no water;
believe me, I feel for the Church to which I am so great a debtor.
This brings to my mind the declaration of our blessed Lord; "`I say unto you,
if ye have faith as a grain of mustard seed, ye shall say unto this mountain,
remove hence, and it shall obey you.`"
I believe this faith will remove mountains of difficulty out of our path heavenward.
But I believe these are for our trial.
I have at times very smooth and quiet seasons,
and I have been made to examine myself to see if I had been in the faith or no;
for the word declares, "`It must be through much tribulation we must enter the kingdom.`"
Dear friend, may thou and thy dear partner, and thy tender offspring,
be enabled with me to give ourselves up as clay in the hands of the potter;
and then whatever besets our path, it will be for us to step over or stumble at,
but not utterly fall;
then shall we go on our way rejoicing in that peace and joy in believing,
and (have) that peace of mind, which passeth all understanding.
Now to Him, who only hath immortality, dwelling in the light,
which no man can approach unto; to Him be honour and power everlasting.

--

William Bush was but little acquainted with the niceties of doctrine; his religion was,
as he stated, one of the heart; what he knew, he knew experimentally;
and it was very evident to many of us, during several subsequent visits,
that he was steadily advancing in his heavenward journey,
rejoicing in the possession of "`the peaceable fruits
of righteousness,`" so that it may be truly said,
that his path was that of the "`just man,
which shineth more and more unto the perfect day.`"
He was much attached to Friends,
and was looking towards joining them at some future period;
the rectitude of their views and practices was increasingly opening to his mind,
and he latterly used the plain language for the most part,
and had mentioned to his wife the prospect of making the external appearance of a Friend.
There was, however, nothing sectarian in his mind;
he loved all those who loved the Lord Jesus Christ in sincerity,
and who showed before men, that they were his disciples,
by the love they had one to another.

Whilst in vigorous health,
it appears that he had repeatedly spoken on the subject of sudden death,
as rather to be desired than dreaded by the children of God; adding, "`sudden death,
sudden glory,`" being permitted to feel in the assurance of living faith,
that the change would be unspeakably glorious.
Four days only before his own death, he attended the funeral of his brother-in-law;
and then expressed to his wife his belief, that he should not long survive, saying,
he supposed he should be laid by the side of his mother in the graveyard at Woolwich.

On the 8th of Second Month, 1844, he was seized with apoplexy when at work,
and died in about twelve hours, not having spoken after he was brought home.
We may rest assured that, however sudden the stroke, it met him fully prepared;
and that he who, whilst amongst us,
rejoiced in commemorating the Lord`'s multiplied mercies,
is now among the ransomed and redeemed "`singing the song of Moses, the servant of God,
and the song of the Lamb, saying, Great and marvellous are thy works, Lord God Almighty;
just and true are all thy ways, thou King of saints.
Who shall not fear thee, O Lord, and glorify thy name?`"

Having now traced "`this monument of the Lord`'s
mercy,`" in his progress from darkness to light,
and from under the power of Satan unto God, it may be well, in conclusion, to inquire,
What instruction is peculiarly to be derived from the narrative?--The same love,
which graciously visited him, is extended to all; and the same divine light,
by which he was illuminated and led, shines into every heart: but how many there are,
who have been convinced of sin by the Holy Spirit,
yet through not abiding under its power, have turned aside,
to depend on the teachings of men,
and have settled down at ease with a merely literal knowledge,
so that the work of conversion has stopped,
and they have fallen short of that establishment in the truth, to which he attained.
We have seen, in his case,
the reality and sufficiency of divine guidance,--the
importance of having the mind steadily directed thereto,
in the early period of discipleship,
and the substantial character and stability of the work, which was effected in him,
by being kept under its influence.
And the language which he, being dead, now speaketh, is, "`Whilst ye have light,
believe in the light, that ye may be the children of light.`"
